//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDemoPractical.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class workernew
    {
        public int WORKER_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public Nullable<int> SALARY { get; set; }
        public string JOINING_DATE { get; set; }
        public string DEPARTMENT { get; set; }
    }
}
